[build]
  command = "npm run build"
  functions = "netlify/functions"

[build]
  command = "cp src/docs/api-doc.yaml ./dist/"
  publish = "dist"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/api-docs"
  to = "/.netlify/functions/api/:splat"
  status = 200