[build]
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[functions."api-docs"]
  included_files = ["docs/api-docs.yaml"]

[functions."list-dir"]
  included_files = ["docs/api-docs.yaml"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/api-docs/*"
  to = "/.netlify/functions/api-docs/:splat"
  status = 200

[[redirects]]
  from = "/list-dir/*"
  to = "/.netlify/functions/list-dir/:splat"
  status = 200